Cypress.Commands.add('projectPage', (projectSelect, amount, creditMaturity) => {
    cy.get('#projectSelect')
        .select(projectSelect)
    cy.get('#amount')
        .select(amount)
    cy.get('#creditMaturity')
        .select(creditMaturity)
})

Cypress.Commands.add("emailConsumer", (emailInput) => {
    cy.get('#email-input')
        .type(emailInput)
        .should('have.value', emailInput)
})

Cypress.Commands.add("maritalStatusConsumer", (maritalStatus, childNumber) => {
    cy.get('#maritalStatus-input')
        .select(maritalStatus)
    cy.get('#childNumberPropal-input')
        .select(childNumber)
})

Cypress.Commands.add("housingStatusConsumer", (housingStatus, housingStatusFromMonth, housingStatusFromYear) => {
    cy.get('#housingStatus-input')
        .select(housingStatus)
    cy.get('#housingStatusFrom-input-month')
        .type(housingStatusFromMonth)
        .should('have.value', housingStatusFromMonth)
    cy.get('#housingStatusFrom-input-year')
        .type(housingStatusFromYear)
        .should('have.value',housingStatusFromYear)
})

Cypress.Commands.add("activityConsumer", (activitySector, profession, businessActivityStartDateMonth, businessActivityStartDateYear) => {
    cy.get('#activitySector-input')
        .select(activitySector)
    cy.get('#profession-input')
        .select(profession)
    cy.get('#businessActivityStartDate-input-month')
        .type(businessActivityStartDateMonth)
        .should('have.value', businessActivityStartDateMonth)
    cy.get('#businessActivityStartDate-input-year')
        .type(businessActivityStartDateYear)
        .should('have.value', businessActivityStartDateYear)
})
Cypress.Commands.add("activityMarriedConsumer", (activitySector, profession, contractType, employedFromMonth,employedFromYear) =>{
    cy.get('#activitySector-input')
        .select(activitySector)
    cy.get('#profession-input')
        .select(profession)
    cy.get('#contractType-input')
        .select(contractType)
    cy.get('#employedFrom-input-month')
        .type(employedFromMonth)
        .should('have.value', employedFromMonth)
    cy.get('#employedFrom-input-year')
        .type(employedFromYear)
        .should('have.value', employedFromYear)
})
Cypress.Commands.add("partnerActivityMarriedConsumer", (partnerActivitySector, partnerProfession,partnerContractType,partnerEmployedFromMonth, partnerEmployedFromYear ) =>{
    cy.get('#partnerActivitySector-input')
        .select(partnerActivitySector)
    cy.get('#partnerProfession-input')
        .select(partnerProfession)
    cy.get('#partnerContractType-input')
        .select(partnerContractType)
    cy.get('#partnerEmployedFrom-input-month')
        .type(partnerEmployedFromMonth)
        .should('have.value', partnerEmployedFromMonth)
    cy.get('#partnerEmployedFrom-input-year')
        .type(partnerEmployedFromYear)
        .should('have.value', partnerEmployedFromYear)
}) 
Cypress.Commands.add("activityPacsConsumer", (activitySector, profession, pensionFromMonth, pensionFromYear) =>{
    cy.get('#activitySector-input')
        .select(activitySector)
    cy.get('#profession-input')
        .select(profession)
    cy.get('#pensionFrom-input-month')
        .type(pensionFromMonth)
        .should('have.value', pensionFromMonth)
    cy.get('#pensionFrom-input-year')
        .type(pensionFromYear)
        .should('have.value', pensionFromYear)
})
Cypress.Commands.add("partnerActivityPacsConsumer", (partnerActivitySector, partnerProfession, partnerContractType, partnerEmployedFromMonth, partnerEmployedFromYear) =>{
    cy.get('#partnerActivitySector-input')
        .select(partnerActivitySector)
    cy.get('#partnerProfession-input')
        .select(partnerProfession)
    cy.get('#partnerContractType-input')
        .type(partnerContractType)
        .should('have.value', partnerContractType)
    cy.get('#partnerEmployedFrom-input-month')
        .type(partnerEmployedFromMonth)
        .should('have.value', partnerEmployedFromMonth)
    cy.get('#partnerEmployedFrom-input-year')
        .type(partnerEmployedFromYear)
        .should('have.value', partnerEmployedFromYear)
})
Cypress.Commands.add("incomConsumer", (mainIncome, housingAssistance, additionalIncome) => {
    cy.get('#mainIncome-input')
        .type(mainIncome)
        .should('have.value', mainIncome)
    cy.get('#housingAssistance-input')
        .type(housingAssistance)
        .should('have.value', housingAssistance)    
    cy.get('#additionalIncome-input')
        .type(additionalIncome)
        .should('have.value', additionalIncome)    
})
Cypress.Commands.add("partnerIncomMarriedAndPacsConsumer", (mainIncome, coIncome) =>{
    cy.get('#mainIncome-input')
        .type(mainIncome)
        .should('have.value', mainIncome)    
    cy.get('#coIncome-input')
        .type(coIncome)
        .should('have.value', coIncome)  
    
})
Cypress.Commands.add('outcomeConsumer', (rentAmount, loanCount, type, loanAmount) => {
    cy.get('#rentAmount-input')
        .type(rentAmount)
        .should('have.value', rentAmount)  
    cy.get('#loanCount-input')
        .select(loanCount)
    cy.get('#type-input')
        .select(type)
    cy.get('#loanAmount-input')
        .type(loanAmount)
        .should('have.value', loanAmount) 
})
Cypress.Commands.add('outcomeMarriedConsumer', (mortgageAmount, loanCount) => {
    cy.get('#mortgageAmount-input')
        .type(mortgageAmount)
        .should('have.value', mortgageAmount) 
    cy.get('#loanCount-input')
        .select(loanCount)
})
Cypress.Commands.add('outcomePacsConsumer', (rentAmount, loanCount) => {
    cy.get('#rentAmount-input')
        .type(rentAmount)
        .should('have.value', rentAmount) 
    cy.get('#loanCount-input')
        .select(loanCount)
})
Cypress.Commands.add('bankConsumer', (bankCode, bankFromYear) => {
    cy.get('#bankCode-input')
        .select(bankCode)
    cy.get('#bankFrom-input-year')
        .type(bankFromYear)
        .should('have.value', bankFromYear) 
})
Cypress.Commands.add('personalInfoConsumer', (gender, lastName, firstName, dateOfBirthDay, dateOfBirthMonth, dateOfBirthYear, postalCode) => {
    cy.get(gender)
        .check({ force: true })
        .should('be.checked')
    cy.get('#lastName-input')
        .type(lastName)
        .should('have.value', lastName) 
    cy.get('#firstName-input')
        .type(firstName)
        .should('have.value', firstName) 
    cy.get('#dateOfBirth-input-day')
        .type(dateOfBirthDay)
        .should('have.value', dateOfBirthDay)
    cy.get('#dateOfBirth-input-month')
        .type(dateOfBirthMonth)
        .should('have.value', dateOfBirthMonth)
    cy.get('#dateOfBirth-input-year')
        .type(dateOfBirthYear)
        .should('have.value', dateOfBirthYear)
    cy.get('#postalCode-input')
        .type(postalCode)
        .should('have.value', postalCode)

})