context('Consumer is married',() => {

  before(() => {
    cy.visit('https://www.younited-credit.com/')
    cy.title()
        .should('include','Le Crédit')
})

it('Choose the project for credit',() => {
    cy.get('#projectSelect')
        .select('NEWCAR')
        .should('contain','Véhicule neuf')
    cy.get('#amount')
        .select('2K')
        .should('contain','2000 €')
    cy.get('#creditMaturity')
        .select('M12')
        .should('contain','12 mois')
    cy.get('[data-di-id=di-id-bca9a80c-4fc29f73]')
        .click()
    cy.url()
        .should('include', '/email')
    cy.get("h2")
        .should('contain', 'Découvrez votre offre de prêt de')
})

it('Email info page',() => {  
  cy.get('#email-input')  
      .type('calypsoatlas63@gmail.com')
      .should('have.value', 'calypsoatlas63@gmail.com')
    cy.wait(2000)
  cy.get('[data-di-id="di-id-8c30ab93-a687b9f3"]')
      .click()
  cy.url()
      .should('include', '/familysituation')
  cy.get("h2")
      .should('contain', 'Votre situation familiale')
})

it('Marital Status',() => {
    cy.get('#maritalStatus-input')
      .select('MARRIED')
      .should('contain', 'Marié(e)')
    cy.get('#childNumberPropal-input')
      .select('0')
      .should('contain','0')
    cy.get('[type="checkbox"]')
      .check({ force: true })
      .should('be.checked') 
    cy.get('[data-test=navigator-compact-forward]')
      .click()
    cy.url()
      .should('include', '/housing')
    cy.get("h2")
      .should('contain', 'Votre logement')

})

it('Housing Status',() => {  
    cy.get('#housingStatus-input')
      .select('HOME_OWNERSHIP_WITH_MORTGAGE')
      .should('contain','Propriétaire (avec crédit immobilier en cours)', {timeout: 1000})
    cy.get('#housingStatusFrom-input-month')
      .type('03')
      .should('have.value', '03')
    cy.get('#housingStatusFrom-input-year')
      .type('2010')
      .should('have.value', '2010')
    cy.get('[type="checkbox"]')
      .uncheck({ force: true })
    cy.get('[data-test=navigator-compact-forward]')
      .click()
    cy.url()
      .should('include', '/professionalsituation')
    cy.get("h2")
      .should('contain', 'Votre situation professionnelle')

})

it('Activity Sector',() => {
    cy.get('#activitySector-input')
      .select('PRIVATE_SECTOR')
      .should('contain','Salarié(e) du secteur privé')
    cy.get('#profession-input')
      .select('SENIOR_EXECUTIVE')
      .should('contain','Cadre supérieur')
    cy.get('#contractType-input')
      .select('CDI')
      .should('contain','CDI')
    cy.get('#employedFrom-input-month')
      .type('09')
      .should('have.value', '09')
    cy.get('#employedFrom-input-year')
      .type('2010')
      .should('have.value', '2010')
    cy.get('[data-test=navigator-compact-forward]')
      .click()
    cy.url()
      .should('include', '/partnerprofession')
    cy.get("h2")
      .should('contain', 'Profession de votre conjoint')

})

it('Partner Activity Sector',() => {
    cy.get('#partnerActivitySector-input')
      .select('PRIVATE_SECTOR')
      .should('contain','Salarié(e) du secteur privé')
    cy.get('#partnerProfession-input')
      .select('SENIOR_EXECUTIVE')
      .should('contain','Cadre supérieur')
    cy.get('#partnerContractType-input')
      .select('CDI')
      .should('contain','CDI')
    cy.get('#partnerEmployedFrom-input-month')
      .type('05')
      .should('have.value', '05')
    cy.get('#partnerEmployedFrom-input-year')
      .type('2000')
      .should('have.value', '2000')
    cy.get('[data-test=navigator-compact-forward]')
      .click()
    cy.url()
      .should('include', '/incomes')
    cy.get("h2")
      .should('contain', 'Vos revenus mensuels')

})

it('Incomes',() => {
    cy.get('#mainIncome-input')
      .type('2200')
      .should('have.value', '2200')
    cy.get('#coIncome-input')
      .type('2300')
      .should('have.value', '2300')
    cy.get('[data-test=navigator-compact-forward]')
      .click()
    cy.url()
      .should('include', '/outcomes')
    cy.get("h2")
      .should('contain', 'Vos charges mensuelles')

})

it('Outcomes',() => {
    cy.get('#mortgageAmount-input')
      .type('780')
      .should('have.value', '780')
    cy.get('#loanCount-input')
      .select('0')
      .should('contain','0')
    cy.get('[data-test=navigator-compact-forward]')
      .click()
    cy.url()
      .should('include', '/bank')
    cy.get("h2")
      .should('contain', 'Votre banque')

})

it('Bank',() => {
    cy.get('#bankCode-input')
      .select('LCL')
      .should('contain','LCL')
    cy.get('#bankFrom-input-year')
      .type('1995')
      .should('have.value', '1995')
    cy.get('[data-test=navigator-compact-forward]')
      .click()
    cy.url()
      .should('include', '/identity')
    cy.get("h2")
      .should('contain','Vos informations')

})

after(() => {
    cy.get('[data-di-id="di-id-66b6d813-77398ce6"]')
      .click()
    cy.get('#lastName-input')
      .type('Kubrick')
      .should('have.value', 'Kubrick')
    cy.get('#firstName-input')
      .type('Tarantino')
      .should('have.value', 'Tarantino')
    cy.get('#dateOfBirth-input-day')
      .type('02')
      .should('have.value', '02')
    cy.get('#dateOfBirth-input-month')
      .type('10')
      .should('have.value', '10')
    cy.get('#postalCode-input')
      .type('33000')
      .should('have.value', '33000')
})
})