context('Consumer is in PACS',() => {

  before(() => {
    cy.visit('https://www.younited-credit.com/')
    cy.title()
        .should('include','Le Crédit')
})

it('Choose the project for credit',() => {
    cy.get('#projectSelect')
        .select('NEWCAR')
        .should('contain','Véhicule neuf')
    cy.get('#amount')
        .select('2K')
        .should('contain','2000 €')
    cy.get('#creditMaturity')
        .select('M12')
        .should('contain','12 mois')
    cy.get('[data-di-id=di-id-bca9a80c-4fc29f73]')
        .click()
    cy.url()
        .should('include', '/email')
    cy.get("h2")
        .should('contain', 'Découvrez votre offre de prêt de')
})

it('Email info page',() => {  
    cy.get('#email-input')  
        .type('calypsoatlas63@gmail.com')
        .should('have.value', 'calypsoatlas63@gmail.com')
    cy.wait(2000)
    cy.get('[data-di-id="di-id-8c30ab93-a687b9f3"]')
        .click()
    cy.url()
        .should('include', '/familysituation')
    cy.get("h2")
        .should('contain', 'Votre situation familiale')
})

it('Marital Status',() => {
    cy.get('#maritalStatus-input')
        .select('COHABITING')
        .should('contain', 'Vie Maritale / PACS')
    cy.get('#childNumberPropal-input')
        .select('0')
        .should('contain','0')
    cy.get('[type="checkbox"]')
        .check({ force: true })
        .should('be.checked') 
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/housing')
    cy.get("h2")
        .should('contain', 'Votre logement')
})

it('Housing Status',() => {  
    cy.get('#housingStatus-input')
        .select('LODGING_PROVIDED_BY_PARTNER')
        .should('contain','Logé(e) par le(la) conjoint(e)', {timeout: 1000})
    cy.get('#housingStatusFrom-input-month')
        .type('05')
        .should('have.value', '05')
    cy.get('#housingStatusFrom-input-year')
        .type('2017')
        .should('have.value', '2017')
    cy.get('[type="checkbox"]')
        .uncheck({ force: true })
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/professionalsituation')
    cy.get("h2")
        .should('contain', 'Votre situation professionnelle')
}) 

it('Activity Sector',() => {
    cy.get('#activitySector-input')
        .select('RETIRED')
        .should('contain','Retraités')
    cy.get('#profession-input')
        .select('RETIRED_FROM_PUBLIC_SECTOR')
        .should('contain','Retraité du secteur public')
    cy.get('#pensionFrom-input-month')
        .type('02')
        .should('have.value', '02')   
    cy.get('#pensionFrom-input-year')
        .type('2018')
        .should('have.value', '2018')
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/partnerprofession')
    cy.get("h2")
        .should('contain', 'Profession de votre conjoint')
})

it('Partner Activity Sector',() => {
    cy.get('#partnerActivitySector-input')
        .select('PUBLIC_SECTOR')
        .should('contain','Salarié(e) du secteur public')
    cy.get('#partnerProfession-input')
        .select('HOSPITAL_CAREGIVER')
        .should('contain','Aide soignant hospitalier')
    cy.get('#partnerContractType-input')
        .select('CDD')
        .should('contain','CDD')
    cy.get('#partnerEmployedFrom-input-month')
        .type('05')
        .should('have.value', '05')
    cy.get('#partnerEmployedFrom-input-year')
        .type('2000')
        .should('have.value', '2000')
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/incomes')
    cy.get("h2")
        .should('contain', 'Vos revenus mensuels')
})

 it('Incomes',() => {
    cy.get('#mainIncome-input')
        .type('2200')
        .should('have.value', '2200')
    cy.get('#coIncome-input')
        .type('5000')
        .should('have.value', '5000')
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/outcomes')
    cy.get("h2")
        .should('contain', 'Vos charges mensuelles')
})

it('Outcomes',() => {
    cy.get('#rentAmount-input')
        .type('900')
        .should('have.value', '900')
    cy.get('#loanCount-input')
        .select('0')
        .should('contain','0')
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/bank')
    cy.get("h2")
        .should('contain', 'Votre banque')
})

it('Bank',() => {
    cy.get('#bankCode-input')
        .select('CREDIT_MUTUEL')
        .should('contain','Credit Mutuel')
    cy.get('#bankFrom-input-year')
        .type('1999')
        .should('have.value', '1999')
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/identity')
    cy.get("h2")
        .should('contain','Vos informations')
})
    after(() => {
    cy.get('[data-di-id="di-id-66b6d813-77398ce6"]')
        .click()
    cy.get('#lastName-input')
        .type('Kubrick')
        .should('have.value', 'Kubrick')
    cy.get('#firstName-input')
        .type('Tarantino')
        .should('have.value', 'Tarantino')
    cy.get('#dateOfBirth-input-day')
        .type('02')
        .should('have.value', '02')
    cy.get('#dateOfBirth-input-month')
        .type('10')
        .should('have.value', '10')
    cy.get('#postalCode-input')
        .type('33000')
        .should('have.value', '33000')
    })
})