context('Consumer is single',() => {

  cy.fixture('mainData.json').as('mainData')

  before(() => {
    cy.visit('https://www.younited-credit.com/')
    cy.title()
        .should('include','Le Crédit')
})

it('Choose the project for credit',() => {
    cy.get('#projectSelect')
        .select('NEWCAR')
        .should('contain','Véhicule neuf')
    cy.get('#amount')
        .select('2K')
        .should('contain','2000 €')
    cy.get('#creditMaturity')
        .select('M12')
        .should('contain','12 mois')
    cy.get('[data-di-id=di-id-bca9a80c-4fc29f73]')
        .click()
    cy.url()
        .should('include', '/email')
    cy.get("h2")
        .should('contain', 'Découvrez votre offre de prêt de')
})

it('Email info page',() => {      
    cy.get('#email-input')  
        .type('calypsoatlas63@gmail.com')
        .should('have.value', 'calypsoatlas63@gmail.com')
    cy.wait(2000)
    cy.get('[data-di-id="di-id-8c30ab93-a687b9f3"]')
        .click()
    cy.url()
        .should('include', '/familysituation')
    cy.get("h2")
        .should('contain', 'Votre situation familiale')
})

it('Marital Status',() => {
    cy.get('#maritalStatus-input')
        .select('SINGLE')
        .should('contain','Célibataire')
    cy.get('#childNumberPropal-input')
        .select('0')
        .should('contain','0')
    cy.get('[type="checkbox"]')
        .check({ force: true })
        .should('be.checked') 
    cy.get('[data-test="navigator-compact-forward"]')
        .click()
    cy.url()
        .should('include', '/housing')
    cy.get("h2")
        .should('contain', 'Votre logement')
})

it('Housing Status',() => {
    cy.get('#housingStatus-input')
        .select('TENANT')
        .should('contain','Locataire', {timeout: 1000})
    cy.get('#housingStatusFrom-input-month')
        .type('01')
        .should('have.value', '01')
    cy.get('#housingStatusFrom-input-year')
        .type('2020')
        .should('have.value', '2020')
    cy.get('[type="checkbox"]')
        .uncheck({ force: true })
    cy.get('[data-test="navigator-compact-forward"]')
        .click()
    cy.url()
        .should('include', '/professionalsituation')
    cy.get("h2")
        .should('contain', 'Votre situation professionnelle')
})

it('Activity Sector',() => {
    cy.get('#activitySector-input')
        .select('INDEPENDENT')
        .should('contain','Indépendants / Travailleurs non salariés')
    cy.get('#profession-input')
        .select('AUTO_ENTREPRENEUR')
        .should('contain','Auto-Entrepreneur')
    cy.get('#businessActivityStartDate-input-month')
        .type('02')
        .should('have.value', '02')
    cy.get('#businessActivityStartDate-input-year')
        .type('2019')
        .should('have.value', '2019')
    cy.get('[data-di-id="di-id-d838032c-320c79b9"]')
        .click()
    cy.get('[data-test="navigator-compact-forward"]')
        .click()
    cy.url()
        .should('include', '/incomes')
    cy.get("h2")
        .should('contain', 'Vos revenus mensuels')
})

it('Incomes',() => {
    cy.get('#mainIncome-input')
        .type('2000')
        .should('have.value', '2000')
    cy.get('#housingAssistance-input')
        .type('0')
        .should('have.value', '0')
    cy.get('#additionalIncome-input')
        .type('0')
        .should('have.value', '0')
    cy.get('[data-test="navigator-compact-forward"]')
        .click()
    cy.url()
        .should('include', '/outcomes')
    cy.get("h2")
        .should('contain','Vos charges mensuelles')
})

it('Outcomes',() => {
    cy.get("h2")
        .should('contain','Vos charges mensuelles')
    cy.get('#rentAmount-input')
        .type('500')
        .should('have.value', '500')
    cy.get('#loanCount-input')
        .select('1')
        .should('contain','1')
    cy.get('#type-input')
        .select('PERSONAL_LOAN')
        .should('contain','Prêt Personnel')
    cy.get('#loanAmount-input')
        .type('20')
        .should('have.value', '20')
    cy.get('[data-test="navigator-compact-forward"]')
        .click()
    cy.url()
        .should('include', '/bank')
    cy.get("h2")
        .should('contain', 'Votre banque')
})

it('Bank',() => {
    cy.get('#bankCode-input')
        .select('HSBC')
        .should('contain','HSBC')
    cy.get('#bankFrom-input-year')
        .type('2010')
        .should('have.value', '2010')
    cy.get('[data-test=navigator-compact-forward]')
        .click()
    cy.url()
        .should('include', '/identity')
    cy.get("h2")
        .should('contain','Vos informations')
})

  after(() => {
    cy.get('#GENDERCODE_M')
        .check({ force: true })
        .should('be.checked')
    cy.get('#lastName-input')
        .type('Kubrick')
        .should('have.value', 'Kubrick')
    cy.get('#firstName-input')
        .type('Tarantino')
        .should('have.value', 'Tarantino')
    cy.get('#dateOfBirth-input-day')
        .type('02')
        .should('have.value', '02')
    cy.get('#dateOfBirth-input-month')
        .type('10')
        .should('have.value', '10')
    cy.get('#postalCode-input')
        .type('33000')
        .should('have.value', '33000')
  })
})